
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Rendy
 */
public class AplikasiKonversiNilaiAngkaKeHuruf extends javax.swing.JFrame {

    private String Huruf;
    /**
     * Creates new form AplikasiKonversiNilaiAngkaKeHuruf
     */

    public AplikasiKonversiNilaiAngkaKeHuruf() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtJmlBayar = new javax.swing.JTextField();
        txtTerbilang = new javax.swing.JTextField();
        cmdkonversi = new javax.swing.JButton();
        cmdbatal = new javax.swing.JButton();
        cmdkeluar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("APLIKASI KONVERSI NILAI ANGKA KE HURUF");

        jLabel2.setText("NILAI ANGKA");

        jLabel3.setText("NILAI HURUF");

        txtJmlBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJmlBayarActionPerformed(evt);
            }
        });
        txtJmlBayar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtJmlBayarKeyTyped(evt);
            }
        });

        cmdkonversi.setText("KONVERSI");
        cmdkonversi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdkonversiActionPerformed(evt);
            }
        });

        cmdbatal.setText("BATAL");
        cmdbatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdbatalActionPerformed(evt);
            }
        });

        cmdkeluar.setText("KELUAR");
        cmdkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdkeluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtJmlBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTerbilang, javax.swing.GroupLayout.PREFERRED_SIZE, 706, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 173, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(cmdkonversi)
                        .addGap(148, 148, 148)
                        .addComponent(cmdbatal)
                        .addGap(222, 222, 222)
                        .addComponent(cmdkeluar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtJmlBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txtTerbilang, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdkonversi)
                    .addComponent(cmdbatal)
                    .addComponent(cmdkeluar))
                .addGap(0, 76, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdkonversiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdkonversiActionPerformed
        BuatHuruf();
        txtTerbilang.setText(Huruf);
    }//GEN-LAST:event_cmdkonversiActionPerformed

    private void BuatHuruf(){
           Huruf = "";
    String nUang = "";
    String spasi = " ";
    String opasi = " ";
    String sUang = txtJmlBayar.getText().replaceAll("\\.","");
    System.err.println("sUang : "+sUang);
    for (int i = 0; i < 9-sUang.length(); i++) {
        opasi+=spasi;
    }
    System.err.println("opasi :"+opasi+"a");
    if (sUang.length()<10){
        nUang=opasi+sUang;
    }else{
        nUang=sUang;
    }
    switch (nUang.substring(9, 10)){
        case "1":
            Huruf = " satu";
            break;
        case "2":
            Huruf = " dua";
            break;
        case "3":
            Huruf = " tiga";
            break;
        case "4":
            Huruf = " empat";
            break;
        case "5":
            Huruf = " lima";
            break;
        case "6":
            Huruf = " enam";
            break;
        case "7":
            Huruf = " tujuh";
            break;
        case "8":
            Huruf = " delapan";
            break;
        case "9":
            Huruf = " sembilan";
            break;
    }
    switch(nUang.substring(8, 9)){
        case "1":
            switch(nUang.substring(9, 10)){
                case "0":
                    Huruf = "Sepuluh";
                    break;
                case "1":
                    Huruf = "Sebelas";
                    break;
                default:
                    Huruf = Huruf+" Belas";
                    break;
            }
            break;
        case "2":
            Huruf = " Dua Puluh"+Huruf;
            break;
        case "3":
            Huruf = " Tiga Puluh"+Huruf;
            break;
        case "4":
            Huruf = " Empat Puluh"+Huruf;
            break;
        case "5":
            Huruf = " Lima Puluh"+Huruf;
            break;
        case "6":
            Huruf = " Enam Puluh"+Huruf;
            break;
        case "7":
            Huruf = " Tujuh Puluh"+Huruf;
            break;
        case "8":
            Huruf = " Delapan Puluh"+Huruf;
            break;
        case "9":
            Huruf = " Sembilan Puluh"+Huruf;
            break;
        case "0":
            switch(nUang.substring(9, 10)){
                case "0":
                    Huruf = "";
                    break;
            }
            break;
    }
    switch(nUang.substring(7, 8)){
        case "1":
            Huruf = " Seratus"+Huruf;
            break;
        case "2":
            Huruf = " Dua Ratus"+Huruf;
            break;
        case "3":
            Huruf = " Tiga Ratus"+Huruf;
            break;
        case "4":
            Huruf = " Empat Ratus"+Huruf;
            break;
        case "5":
            Huruf = " Lima Ratus"+Huruf;
            break;
        case "6":
            Huruf = " Enam Ratus"+Huruf;
            break;
        case "7":
            Huruf = " Tujuh Ratus"+Huruf;
            break;
        case "8":
            Huruf = " Delapan Ratus"+Huruf;
            break;
        case "9":
            Huruf = " Sembilan Ratus"+Huruf;
            break;
        case "0":
            switch(nUang.substring(8, 10)){
                case "00":
                    Huruf = "";
                    break;
            }
            break;
    }
    switch(nUang.substring(6, 7)){
        case "1":
            if (Integer.parseInt(nUang.trim())<2000 || nUang.substring(4, 6).equals("00")){
                Huruf = " Seribu"+Huruf;
            }else{
                Huruf = " Satu Ribu"+Huruf;
            }
            break;
        case "2":
            Huruf = " Dua Ribu"+Huruf;
            break;
        case "3":
            Huruf = " Tiga Ribu"+Huruf;
            break;
        case "4":
            Huruf = " Empat Ribu"+Huruf;
            break;
        case "5":
            Huruf = " Lima Ribu"+Huruf;
            break;
        case "6":
            Huruf = " Enam Ribu"+Huruf;
            break;
        case "7":
            Huruf = " Tujuh Ribu"+Huruf;
            break;
        case "8":
            Huruf = " Delapan Ribu"+Huruf;
            break;
        case "9":
            Huruf = " Sembilan Ribu"+Huruf;
            break;
        case "0":
            Huruf = " Ribu"+Huruf;
            break;
    }
    switch(nUang.substring(5, 6)){
        case "1":
            if (nUang.substring(6, 7).equals("0")){
                Huruf = " Sepuluh"+Huruf;
            }else{
                if (nUang.substring(6, 7).equals("1")){
                    Huruf = " Sebelas"+Huruf.substring(5, Huruf.length());
                }else{
                    Huruf = Huruf.substring(0, Huruf.indexOf("Ribu")-1)+" Belas "+Huruf.substring(Huruf.indexOf("Ribu"), Huruf.length()).trim();
                }
            }
            break;
        case "2":
            Huruf = " Dua Puluh"+Huruf;
            break;
        case "3":
            Huruf = " Tiga Puluh"+Huruf;
            break;
        case "4":
            Huruf = " Empat Puluh"+Huruf;
            break;
        case "5":
            Huruf = " Lima Puluh"+Huruf;
            break;
        case "6":
            Huruf = " Enam Puluh"+Huruf;
            break;
        case "7":
            Huruf = " Tujuh Puluh"+Huruf;
            break;
        case "8":
            Huruf = " Delapan Puluh"+Huruf;
            break;
        case "9":
            Huruf = " Sembilan Puluh"+Huruf;
            break;
    }
    switch(nUang.substring(4, 5)){
        case "0":
            Huruf=Huruf.replaceAll("Ribu", "");
            break;
        case "1":
            Huruf = " Seratus"+Huruf;
            break;
        case "2":
            Huruf = " Dua Ratus"+Huruf;
            break;
        case "3":
            Huruf = " Tiga Ratus"+Huruf;
            break;
        case "4":
            Huruf = " Empat Ratus"+Huruf;
            break;
        case "5":
            Huruf = " Lima Ratus"+Huruf;
            break;
        case "6":
            Huruf = " Enam Ratus"+Huruf;
            break;
        case "7":
            Huruf = " Tujuh Ratus"+Huruf;
            break;
        case "8":
            Huruf = " Delapan Ratus"+Huruf;
            break;
        case "9":
            Huruf = " Sembilan Ratus"+Huruf;
            break;
    }
    switch(nUang.substring(3, 4)){
        case "1":
            Huruf = " Satu Juta"+Huruf;
            break;
        case "2":
            Huruf = " Dua Juta"+Huruf;
            break;
        case "3":
            Huruf = " Tiga Juta"+Huruf;
            break;
        case "4":
            Huruf = " Empat Juta"+Huruf;
            break;
        case "5":
            Huruf = " Lima Juta"+Huruf;
            break;
        case "6":
            Huruf = " Enam Juta"+Huruf;
            break;
        case "7":
            Huruf = " Tujuh Juta"+Huruf;
            break;
        case "8":
            Huruf = " Delapan Juta"+Huruf;
            break;
        case "9":
            Huruf = " Sembilan Juta"+Huruf;
            break;
    }
    switch(nUang.substring(2, 3)){
        case "1":
            if (nUang.substring(3, 4).equals("0")){
                Huruf = " Sepuluh Juta"+Huruf;
            }else{
                if (nUang.substring(3, 4).equals("1")){
                    Huruf = " Sebelas"+Huruf.substring(5, Huruf.length());
                }else{
                    Huruf = Huruf.substring(0, Huruf.indexOf("Juta")-1)+" Belas "+Huruf.substring(Huruf.indexOf("Juta"), Huruf.length());
                }
            }
            break;
        case "2":
            if (nUang.substring(3, 4).equals("0")){
                Huruf = " Dua Puluh Juta"+Huruf;
            }else{
                Huruf = "Dua Puluh"+Huruf;
            }
            break;
        case "3":
            if (nUang.substring(3, 4).equals("0")){
                Huruf = " Tiga Puluh Juta"+Huruf;
            }else{
                Huruf = "Tiga Puluh"+Huruf;
            }
            break;
        case "4":
            if (nUang.substring(3, 4).equals("0")){
                Huruf = " Empat Puluh Juta"+Huruf;
            }else{
                Huruf = "Empat Puluh"+Huruf;
            }
            break;
        case "5":
            if (nUang.substring(3, 4).equals("0")){
                Huruf = " Lima Puluh Juta"+Huruf;
            }else{
                Huruf = "Lima Puluh"+Huruf;
            }
            break;
        case "6":
            if (nUang.substring(3, 4).equals("0")){
                Huruf = " Enam Puluh Juta"+Huruf;
            }else{
                Huruf = "Enam Puluh"+Huruf;
            }
            break;
        case "7":
            if (nUang.substring(3, 4).equals("0")){
                Huruf = " Tujuh Puluh Juta"+Huruf;
            }else{
                Huruf = "Tujuh Puluh"+Huruf;
            }
            break;
        case "8":
            if (nUang.substring(3, 4).equals("0")){
                Huruf = " Delapan Puluh Juta"+Huruf;
            }else{
                Huruf = "Delapan Puluh"+Huruf;
            }
            break;
        case "9":
            if (nUang.substring(3, 4).equals("0")){
                Huruf = " Sembilan Puluh Juta"+Huruf;
            }else{
                Huruf = "Sembilan Puluh"+Huruf;
            }
            break;
        case "0":
            if (nUang.substring(3, 4).equals("0")){
                Huruf = " Juta"+Huruf;
            }
            break;
    }
    switch(nUang.substring(1,2)){
        case "1":
            Huruf = " Seratus"+Huruf;
            break;
        case "2":
            Huruf = " Dua Ratus"+Huruf;
            break;
        case "3":
            Huruf = " Tiga Ratus"+Huruf;
            break;
        case "4":
            Huruf = " Empat Ratus"+Huruf;
            break;
        case "5":
            Huruf = " Lima Ratus"+Huruf;
            break;
        case "6":
            Huruf = " Enam Ratus"+Huruf;
            break;
        case "7":
            Huruf = " Tujuh Ratus"+Huruf;
            break;
        case "8":
            Huruf = " Delapan Ratus"+Huruf;
            break;
        case "9":
            Huruf = " Sembilan Ratus"+Huruf;
            break;
        case "0":
            if (nUang.substring(3, 4).equals("0")){
                Huruf = Huruf.replace("Juta", "");
            }
            break;
    }
    switch (nUang.substring(0, 1)){
        case "1":
            Huruf = " Satu Milyar"+Huruf;
            break;
        case "2":
            Huruf = " Dua Milyar"+Huruf;
            break;
        case "3":
            Huruf = " Tiga Milyar"+Huruf;
            break;
        case "4":
            Huruf = " Empat Milyar"+Huruf;
            break;
        case "5":
            Huruf = " Lima Milyar"+Huruf;
            break;
        case "6":
            Huruf = " Enam Milyar"+Huruf;
            break;
        case "7":
            Huruf = " Tujuh Milyar"+Huruf;
            break;
        case "8":
            Huruf = " Delapan Milyar"+Huruf;
            break;
        case "9":
            Huruf = " Sembilan Milyar"+Huruf;
            break;
    }
    if (Double.parseDouble(sUang)==0){
        Huruf = "Nol";
    }
}
    private void cmdbatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdbatalActionPerformed
        // TODO add your handling code here:
        txtJmlBayar.setText("");
        txtTerbilang.setText("");
        txtJmlBayar.requestFocus();
    }//GEN-LAST:event_cmdbatalActionPerformed

    private void cmdkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdkeluarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_cmdkeluarActionPerformed

    private void txtJmlBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJmlBayarActionPerformed

    }//GEN-LAST:event_txtJmlBayarActionPerformed

    private void txtJmlBayarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtJmlBayarKeyTyped
      if (txtJmlBayar.getText().length()>9) {
      JOptionPane.showMessageDialog(null,"Sepurane !!! Max 10 Angka nggih ..");
      evt.consume();
      }
    }//GEN-LAST:event_txtJmlBayarKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AplikasiKonversiNilaiAngkaKeHuruf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AplikasiKonversiNilaiAngkaKeHuruf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AplikasiKonversiNilaiAngkaKeHuruf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AplikasiKonversiNilaiAngkaKeHuruf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AplikasiKonversiNilaiAngkaKeHuruf().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdbatal;
    private javax.swing.JButton cmdkeluar;
    private javax.swing.JButton cmdkonversi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtJmlBayar;
    private javax.swing.JTextField txtTerbilang;
    // End of variables declaration//GEN-END:variables
}
